SaitCourses/Controllers/TShirtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SaitCourses.Models;
using SaitCourses.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Web;
using SaitCourses;
using SaitCourses.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using System.Net;
using Hanssens.Net;

namespace SaitCourses.Controllers
{
    public class TShirtController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly IConfiguration Configuration;
        private readonly UserManager<User> _userManager;        
        public TShirtController(ApplicationContext db, UserManager<User> userManager, IConfiguration configuration)
        {
            _db = db;
            _userManager = userManager;
            Configuration = configuration;
        }
        private void deleteShirt(int id)
        {
            var rating = _db.ratings.FirstOrDefault(item => item.shirtid == id);
            var tshirt =  _db.tshirts.Find(id);
            if (rating != null)
            {
                _db.ratings.Remove(rating);
                _db.SaveChanges();
            }
            if (tshirt != null)
            {
                _db.tshirts.Remove(tshirt);
                _db.SaveChanges();
            }
        }
        private void CreateTopicAddDb(string name)
        {
            var topic = _db.topics.FirstOrDefault(item => item.nameTopic == name);
            if (topic == null)
            {
                _db.topics.Add(new Topic { nameTopic = name });
                _db.SaveChanges();
            }
        }
        private string GetTagsEditConstructor(int id)
        {
            var TagInShirtId = _db.tagInTShirts.Where(item => item.shirtid == id).ToArray();
            string tags = "";
            for (int i = 0; i < TagInShirtId.Length; i++)
                tags += " "+ _db.tags.FirstOrDefault(item => item.id == TagInShirtId[i].tagid).name.ToString();
            return tags;
        }
        private TShitsViewModel ShowConstructor(int id, string returnUrl, string userId)
        {
            string[] topics = _db.topics.Select(item => item.nameTopic).ToArray();

            if (id == 0)
            {
                return new TShitsViewModel
                {
                    returnUrl = returnUrl,
                    userid = userId,
                    Topics = topics,
                    Tegs = _db.tags.Select(item => item.name).ToArray(),
                    tag = _db.tags.ToArray()
                };
            }
            else
            {
                Shirt shirt =  _db.tshirts.Find(id);
                return new TShitsViewModel
                {
                    userid = userId,
                    returnUrl = returnUrl,
                    id = shirt.id,
                    image = shirt.image,
                    TShirtName = shirt.name,
                    description = shirt.description,
                    Topics = topics,
                    Tag = GetTagsEditConstructor(id),
                };
            }
        }
        private void ChangingParametersShirt(TShitsViewModel model, User user)
        {
            var result = _db.tshirts.FirstOrDefault(item => item.id == model.id);
            var topics = _db.topics.FirstOrDefault(item => item.nameTopic == model.Topic);
            result.name = model.TShirtName;
            result.description = model.description;
            result.themeId = topics.id;
            result.createDate = DateTime.Now.ToString("MM/dd/yyyy");
            result.Sex = model.sex;
            _db.tshirts.Update(result);
            _db.SaveChanges();
        }
        private string[] GetTegsEdit(TShitsViewModel model)
        {
            string tag = model.Tag.Replace("  ", " ");
            string[] tags = tag.Split(' ');
            return tags;
        }
        private void AddTagsEdit(TShitsViewModel model)
        {
            string[] tags = GetTegsEdit(model);
            for (int i = 0; i < tags.Length; i++)
            {
                if (_db.tags.FirstOrDefault(item => item.name == tags[i]) == null)
                {
                    _db.tags.Add(new Tag { name = tags[i] });
                    _db.SaveChanges();
                }
                Shirt shirt = _db.tshirts.FirstOrDefault(item => item.name == model.TShirtName);
                Tag tag1 = _db.tags.FirstOrDefault(item => item.name == tags[i]);
                _db.tagInTShirts.Add(new TagInTShirt
                {
                    shirtid = shirt.id,
                    tagid = tag1.id
                });
                _db.SaveChanges();
            }
        }
        private BasketViewModel GetShoppingList(User user)
        {
            var _basket = _db.baskets.Where(item => item.userId == user.Id).ToList();
            return new BasketViewModel
            {
                userId = user.Id,
                basket = _basket.ToList()
            };
        }
        private void AddBasket(BasketViewModel model, User user, int id)
        {
            var result = _db.tshirts.FirstOrDefault(item => item.id == id);
            _db.baskets.Add(new Basket
            {
                dataOfPurchase = DateTime.Now.ToString("MM/dd/yyyy"),
                nameShirt = result.name,
                amount = 1,
                shirtid = result.id,
                userId = user.Id,
                purchaseStatus = false,
                sex = model.sex,
                size = model.size

            });
            _db.SaveChanges();
        }
        private async Task<User> GetUser()
        {
            User user = await _userManager.GetUserAsync(User);
            return user;
        }
        private async void BayAuthenticated(User user)
        {
            var result = _db.baskets.Where(item => item.userId == user.Id 
                && item.purchaseStatus == false).ToList();
            string message = "";
            foreach (var status in result)
            {
                status.purchaseStatus = true;
                message += "\n" + status.nameShirt.ToString() + ", price 30 $";
                _db.baskets.Update(status);
                _db.SaveChanges();
            }
            EmailService emailservice = new EmailService(Configuration);
            await emailservice.SendEmailAsync(user.Email, "Purchase",
                "you bought t-shirts: " + message);
        }
        private async void BayNoAuthenticated(BasketViewModel model)
        {
            string message = model.noAutorize;
            EmailService emailservice = new EmailService(Configuration);
            await emailservice.SendEmailAsync(model.Email, "Purchase",
                "you bought t-shirts: " + message);
        }
        private string UserVerificationAndPurchase(BasketViewModel model, User user)
        {
            if (User.Identity.IsAuthenticated)
            {
                BayAuthenticated(user);
                return "Bay";
            }
            else
            {
                if (ModelState.IsValid)
                {
                    BayNoAuthenticated(model);
                    return "Bay";
                }
                else
                    return "Basket";
            }
        }

        [TypeFilter(typeof(UserFilters))]
        public IActionResult Delete(int id, string returnUrl)
        {
            deleteShirt(id);
            return Redirect(returnUrl);
        }

        public IActionResult CreateTopic() => View();

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateTopic(string name)
        {

            CreateTopicAddDb(name);
            return RedirectToAction("Index", "Home");
        }

        [TypeFilter(typeof(UserFilters))]
        public IActionResult Constructor(int id, string returnUrl, string userId)
        {
            return View(ShowConstructor(id, returnUrl, userId));
        }

        [HttpPost]
        [TypeFilter(typeof(UserFilters))]
        public async Task<IActionResult> Edit(TShitsViewModel model, string returnUrl)
        {      
            ChangingParametersShirt(model, await GetUser());
            if(!String.IsNullOrEmpty(model.Tag))
               AddTagsEdit(model);
            return Redirect(returnUrl);
        }

        public async Task<IActionResult> Stores()
        {
            return View(GetShoppingList(await GetUser())) ;
        }
        [HttpGet]
        public async Task<IActionResult> basket()
        {
            if(User.Identity.IsAuthenticated)
                return View(GetShoppingList(await GetUser()));
            else
                return View("Basket");
        }
        
        [HttpPost]
        public async Task<IActionResult> basket(int id, BasketViewModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                AddBasket(model, await GetUser(), id);
                return View(GetShoppingList(await GetUser()));
            }
            else
                return View("Basket");
        }
        
        [HttpPost]
        [TypeFilter(typeof(UserFilters))]
        public async Task<IActionResult> DeleteBasket(int id)
        {
            var result = _db.baskets.FirstOrDefault(item => item.id == id);
            _db.baskets.Remove(result);
            await _db.SaveChangesAsync();
            return RedirectToAction("basket");
        }

        [HttpPost]
        public async Task<IActionResult> Bay(BasketViewModel model, string messageBasket)
        {
            return View(UserVerificationAndPurchase(model, await GetUser()));
        }

        [TypeFilter(typeof(UserFilters))]
        public IActionResult Index() => View(_db.images.ToList());

        [TypeFilter(typeof(UserFilters))]
        public IActionResult EditShirt()
        {
            return RedirectToAction("Index", "Home");
        }

SaitCourses/Views/TShirt/Constructor.cshtml
@model SaitCourses.ViewModels.TShitsViewModel
<!DOCTYPE html>
<html>
<head>
    <title>lego</title>
    <link href="https://fonts.googleapis.com/css?family=Almarai:700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css.css" type="text/css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script type="text/javascript" src="js.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.4.0/fabric.min.js"></script>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
</head>
<body>
    <div class="container marginT50 dropzone">
        <div class="row">
            <div class="col-sm">
                @if (Model.description == null)
                {
                    <canvas id="canvas" width="500px" height="500px"></canvas>
                    <div id="containerTag" style="display: flex; flex-wrap: wrap; padding: 5px; padding-top: 10px;"></div>
                }
                else
                {
                    <img src="@Model.image.Replace(".svg", ".png")" width="500px" height="500px"></img>
                    <div id="containerTag" style="display: flex; flex-wrap: wrap; padding: 5px; padding-top: 10px;"></div>
                }
            </div>
            <div class="col-sm">
                <div>
                    @if (Model.description == null)
                    {
                        <form class="my-form" method="post" asp-controller="Image" asp-action="Constructor" asp-route-returnUrl="@Model.returnUrl" asp-route-userId="@Model.userid">
                            <h2 id="Tname">T-Shirts name:</h2>
                            <input class="form-control" asp-for="TShirtName" placeholder="Name" type="text">
                            <p>Description:</p>
                            <textarea class="form-control" asp-for="description" placeholder="Description" type="text"></textarea>
                            <p>Topic:</p>
                            <input id="imageLink" asp-for="image" hidden />
                            <select class="form-control field-input mb-2" asp-for="Topic">
                                <option class="form-control" value="@Model.Topics[0]">@Model.Topics[0]</option>
                                @for (int i = 1; i < Model.Topics.Length; i++)
                                {
                                    <option class="form-control" value="@Model.Topics[i]">@Model.Topics[i]</option>
                                }
                            </select>
                            <button type="submit" id="imageLink2" hidden></button>
                            <p>Tags:</p>
                            <input class="form-control" asp-for="Tag" value="@Model.Tag" id="inputTag" placeholder="#itra" onchange="tag()" />

                            <hr id="line">
                        </form>
                    }
                    else
                    {
                <form class="my-form" method="post" asp-controller="TShirt" asp-action="Edit" asp-route-id="@Model.id" asp-route-returnUrl="@Model.returnUrl" asp-route-userId="@Model.userid">
                    <h2 id="Tname">T-Shirts name:</h2>
                    <input class="form-control" asp-for="TShirtName" placeholder="Name" value="@Model.TShirtName" type="text">
                    <p>Description:</p>
                    <textarea class="form-control" asp-for="description" type="text"></textarea>
                    <p>Topic:</p>
                    <input id="imageLink" asp-for="image" hidden />
                    <select class="form-control field-input mb-2" asp-for="Topic">
                        <option class="form-control" value="@Model.Topics[0]">@Model.Topics[0]</option>
                        @for (int i = 1; i < Model.Topics.Length; i++)
                        {
                            <option class="form-control" value="@Model.Topics[i]">@Model.Topics[i]</option>
                        }
                    </select>
                    <button type="submit" id="imageLink2" hidden></button>
                    <p>Tags:</p>
                    <input class="form-control" type="text" value="@Model.Tag" asp-for="Tag" id="inputTag" onchange="tag()" />
                    <script>window.onload(tag())</script>
                    <hr id="line">
                    <div class=".col-3 q">
                        <button class="btn" onclick="save()">Save</button>
                    </div>
                </form>
                    }
                </div>
                @if (Model.description == null)
                {
                    <div class="container">
                        <!-- ---------------------------------------------------------------------------------- -->
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="radio" name="r" value="l" onchange="check()">Man
                                <!--<input type="radio" name="sex" id="option1" autocomplete="off" checked onclick="check()">-->
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="r" value="2" onchange="check()">Women
                                <!--<input type="radio" name="sex" id="option2" autocomplete="off" onclick="check()">-->
                            </label>
                        </div>
                        <p></p>
                        <!-------------------------------------------------------------------------------------  -->
                        <!-- ---------------------------------------------------------------------------------- -->
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="radio" name="filter" value="blackAndWhite" onchange="changeImageFilter('blackAndWhite')">Black & White
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="filter" value="sepia" onchange="changeImageFilter('sepia')">Sepia
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="filter" value="pixelate" onchange="changeImageFilter('pixelate')">Pixelate
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="filter" value="none" onchange="changeImageFilter('none')">NONE
                            </label>
                        </div>


                        <!-------------------------------------------------------------------------------------  -->
                        <div class="container col">

                            <div class=".col-3 q">
                                <p class="">Color text:   <input type="color" class="form-control" style="display:grid" id="favcolor"></p>
                            </div>
                            <div class=".col-3 q">
                                <p class="">T-color: <input type="color" class="form-control" id="tcolor"></p>
                            </div>
                            <div class="row">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroupFileAddon01"></span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="file">
                                        <label class="fa fa-cloud-upload custom-file-label form-control">Choose file</label>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class=".col-3 q">
                                    <button class="	btn btn-danger" onclick="f()">Delete object</button>
                                </div>
                                <div class=".col-3 q">
                                    <button class="btn" onclick="text()">Add text</button>
                                </div>
                            </div>
                        </div>

                        <div class=".col-3 q">
                            <button class="btn" onclick="save()">Save</button>
                        </div>
                    </div>
                }
                </div>
        </div>
    </div>

    <div class="container">
        <hr id="line">
    </div>
    <div class="progress-bar" id="progress-bar">
        <div class="progress" id="progress"></div>
    </div>


</body>
</html>



<script>
    autocomplete(document.getElementById("myInput"), @Model.);
</script> 
<script>
    function tag() {
        let containerTag = document.getElementById("containerTag");
        containerTag.innerHTML = "";
        let text = document.getElementById("inputTag").value;
        text = text.replace('  ', ' ');
        if (text != "") {
            let word = text.split(' ');

            for (i = 0; i < word.length; i++) {
                if (word[i].Trim !== '') {
                    let div = document.createElement("div");
                    div.innerHTML = "<div class=\"styleTag\" style=\"padding: 2px; border: 2px solid black; border-radius: 10px; margin-right: 10px; margin-bottom: 5px;\">" + word[i] + "</div>";
                    containerTag.appendChild(div);
                }
            }
        }
    }
</script>
<script type="text/javascript" scr="~/js/autocomplete.js"></script>
<script type="text/javascript" src="~/js/Constructor.js"></script>

SaitCourses/Views/TShirt/CreateTopic.cshtml
@model string

<form asp-action="CreateTopic" method="post">
    <div class="form-group">
        <label for="name">New topic</label>
        <input name="name" class="form-control"/>
    </div>
    <button type="submit" class="btn btn-outline-primary">Add</button>
</form>

SaitCourses/Views/TShirt/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

<h2>List role</h2>
<table class="table">
    @foreach(var role in Model)
    {
        <tr>
            <td>@role.Name</td>
            <td>
                <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-outline-danger">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>
<a class="btn btn-outline-primary" asp-action="Create">Add role</a>
<a class="btn btn-outline-primary" asp-action="UserList">User List</a>

SaitCourses/Views/TShirt/ShirtEdit.cshtml
@model SaitCourses.ViewModels.TShitsViewModel
<!DOCTYPE html>
<html>
<head>
    <title>lego</title>
    <link href="https://fonts.googleapis.com/css?family=Almarai:700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css.css" type="text/css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script type="text/javascript" src="js.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.4.0/fabric.min.js"></script>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
</head>
<body>

    <div class="container marginT50 dropzone">
        <div class="row">
            <div class="col-sm">
                <canvas id="canvas" width="500px" height="500px" src="@Model.image.Replace(".svg",".png")"></canvas>
            </div>
            <div class="col-sm">
                <div class="container">
                    <form class="my-form" method="post" asp-controller="TShirt" asp-action="Edit" asp-route-id="@Model.id" asp-route-returnUrl="@Model.returnUrl">
                        <h2 id="Tname">T-Shirts name:</h2>
                        <input asp-for="TShirtName" type="text">
                        <p>Description:</p>
                        <input asp-for="description" type="text">
                        <p>Topic:</p>
                        <input id="imageLink" asp-for="image" hidden />
                        <select class="form-control field-input mb-5 col-md-6" asp-for="Topic">
                            <option value="@Model.Topics[0]">@Model.Topics[0]</option>
                            @for (int i = 1; i < Model.Topics.Length; i++)
                            {
                                <option value="@Model.Topics[i]">@Model.Topics[i]</option>
                            }
                        </select>

                        @*<button type="submit" id="imageLink2" hidden></button>*@
                        <div id="containerTag" style="display: flex; flex-wrap: wrap; padding: 5px; padding-top: 10px;"></div>

                        <div>
                            <input asp-for="Tag" id="inputTag" onchange="tag()" />
                        </div>

                        <script>
                            function tag() {
                                let containerTag = document.getElementById("containerTag");
                                containerTag.innerHTML = "";
                                let text = document.getElementById("inputTag").value;
                                text = text.replace('  ', ' ');
                                let word = text.split(' ');
                                for (i = 0; i < word.length; i++) {
                                    if (word[i].Trim !== '') {
                                        let div = document.createElement("div");
                                        div.innerHTML = "<div class=\"styleTag\" style=\"padding: 2px; border: 2px solid black; border-radius: 10px; margin-right: 10px; margin-bottom: 5px;\">" + word[i] + "</div>";
                                        containerTag.appendChild(div);
                                    }
                                }
                            }
                        </script>


                        <hr id="line">


                        <!-- ---------------------------------------------------------------------------------- -->
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="radio" name="r" value="l" onchange="check()">Man
                                <!--<input type="radio" name="sex" id="option1" autocomplete="off" checked onclick="check()">-->
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="r" value="2" onchange="check()">Women
                                <!--<input type="radio" name="sex" id="option2" autocomplete="off" onclick="check()">-->
                            </label>
                        </div>
                        <!-------------------------------------------------------------------------------------  -->
                        <!-- ---------------------------------------------------------------------------------- -->
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active">
                                <input type="radio" name="filter" value="blackAndWhite" onchange="changeImageFilter('blackAndWhite')">Black & White
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="filter" value="sepia" onchange="changeImageFilter('sepia')">Sepia
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="filter" value="pixelate" onchange="changeImageFilter('pixelate')">Pixelate
                            </label>
                            <label class="btn btn-secondary">
                                <input type="radio" name="filter" value="none" onchange="changeImageFilter('none')">NONE
                            </label>
                        </div>


                        <!-------------------------------------------------------------------------------------  -->
                        <div class="container">
                            <div class="row">
                                <div class=".col-3 q">
                                    <p class="">Color object:   <input type="color" class="" id="favcolor"></p>
                                </div>
                                <div class=".col-3 q">
                                    <p class="">T-color: <input type="color" class="" id="tcolor"></p>
                                </div>
                                <div class=".col-3 q">
                                    <label class="custom-file-upload">
                                        <input type="file" id="file" />
                                        <i class="fa fa-cloud-upload"></i>Upload File
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class=".col-3 q">
                                    <button class="btn" type="submit" @*onclick="save()*@">Save</button>
                                </div>
                                <div class=".col-3 q">
                                    <button class="	" onclick="f()">Delete selected object</button>
                                </div>
                                <div class=".col-3 q">
                                    <button class="" onclick="text()">Add text</button>
                                </div>
                            </div>
                        </div>
                        <button id="add" class="font700">Add to Bag</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <hr id="line">
    </div>
    <div class="container">
        <div class="input-group mb-3">
            <input type="text" class="form-control" id="inputComment">
            <div class="input-group-append">
                <button id="comment" class="">Button</button>
            </div>
            <div class="progress" id="progress"></div>
        </div>
    </div>

    <script>$('.file-upload').file_upload();</script>
    <div class="file-upload-wrapper">
        <input type="file" id="input-file-now" class="file-upload" />
    </div>


    <form action="/file-upload"
          class="dropzone"
          id="my-awesome-dropzone"></form>

    <div id="dropbox">
        <h1 class="text-center">Upload files</h1>
        <form class="my-form">
            <div class="form_line">
                <div class="form_controls">
                    <div class="upload_button_holder">

                        <input type="file" id="fileElem" multiple accept="image/*" style="display:none" onchange="handleFiles(this.files)">
                        <img id="temp" src="" />
                        <a href="#" id="fileSelect">Select some files</a>
                    </div>
                </div>
            </div>
            <button type="submit">Save</button>
        </form>
        <div class="progress-bar" id="progress-bar">
            <div class="progress" id="progress"></div>
        </div>
        <div id="gallery" />
    </div>

</body>
</html>




<script type="text/javascript" src="~/js/Constructor.js"></script>